### ISSUE TITLE
Hello, I have trobule in pushing twilio project.

### ISSUE THREAD

**Issue by lovelyCreator** [lovelyCreator/booksmart-backend#1]
Hello everyone. I have experiences in twilio project.
When, I pushed it, there is an error that the project include private information.
Why?
Please help me.

**Comment by snowangel3339** [comment]
You can make .env file and save all private information like Twillio AccountSid and AuthToken.
I

**Comment by lovelyCreator** [comment]
I tried and it was successful.
Thanks.
